import { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { LOCATIONS } from '../services/routes';

export default function Home() {
  const [locations, setLocations] = useState([]);

  useEffect(() => {
    (async () => {
      const locations = await LOCATIONS.getList();
      if (locations) setLocations(locations);
    })();
  }, []);
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Trabalho Final IoT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Trabalho Final de IoT
        </h1>

        <p className={styles.description}>
          Localizações Salvas
        </p>

        {locations.map((location, index) => {
          return (
            <code key={index} className={styles.code}>Lat: {location.lat} Lng: {location.lng}</code>
          );
        })}   
        
        <div className={styles.grid}>
          <a href="locations" className={styles.card}>
            <h2>Em lista &rarr;</h2>
            <p>Lista com todos os pontos salvos.</p>
          </a>
        </div>
      </main>
    </div>
  )
}
