import { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { LOCATIONS } from '../services/routes';

export default function Home() {
  const [last_location, setLastLocation] = useState([]);

  useEffect(() => {
    (async () => {
      const locations = await LOCATIONS.getList();
      if (locations) {
        setLastLocation(locations[locations.length-1])
      };
    })();
  }, []);
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Trabalho Final IoT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Trabalho Final de IoT
        </h1>

        <p className={styles.description}>
          Última localização
        </p>

        <code className={styles.code}>Lat: {last_location.lat} Lng: {last_location.lng}</code>
        
        <div className={styles.grid}>
          <a href="locations" className={styles.card}>
            <h2>Lista Completa &rarr;</h2>
            <p>Lista com todos os pontos salvos.</p>
          </a>
        </div>
      </main>
    </div>
  )
}
